// Generated by CoffeeScript 1.9.1
var slice = [].slice;

require("source-map-support").install();

module.exports = function() {
  var what;
  what = 1 <= arguments.length ? slice.call(arguments, 0) : [];
  return {};
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguY29mZmVlIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiaW5kZXguY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxJQUFBLGdCQUFBOztBQUFBLE9BQUEsQ0FBUSxvQkFBUixDQUE2QixDQUFDLE9BQTlCLENBQUEsQ0FBQSxDQUFBOztBQUFBLE1BRU0sQ0FBQyxPQUFQLEdBQWlCLFNBQUEsR0FBQTtBQUFhLE1BQUEsSUFBQTtBQUFBLEVBQVosNERBQVksQ0FBQTtTQUFBLEdBQWI7QUFBQSxDQUZqQixDQUFBIiwic291cmNlc0NvbnRlbnQiOlsicmVxdWlyZShcInNvdXJjZS1tYXAtc3VwcG9ydFwiKS5pbnN0YWxsKClcblxubW9kdWxlLmV4cG9ydHMgPSAod2hhdC4uLikgLT4ge31cbiJdfQ==