// Generated by CoffeeScript 1.9.1
var slice = [].slice;

require("source-map-support").install();

module.exports = function() {
  var what;
  what = 1 <= arguments.length ? slice.call(arguments, 0) : [];
  throw new Error("error");
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguY29mZmVlIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiaW5kZXguY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxJQUFBLGdCQUFBOztBQUFBLE9BQUEsQ0FBUSxvQkFBUixDQUE2QixDQUFDLE9BQTlCLENBQUEsQ0FBQSxDQUFBOztBQUFBLE1BRU0sQ0FBQyxPQUFQLEdBQWlCLFNBQUEsR0FBQTtBQUNmLE1BQUEsSUFBQTtBQUFBLEVBRGdCLDREQUNoQixDQUFBO0FBQUEsUUFBVSxJQUFBLEtBQUEsQ0FBTSxPQUFOLENBQVYsQ0FEZTtBQUFBLENBRmpCLENBQUEiLCJzb3VyY2VzQ29udGVudCI6WyJyZXF1aXJlKFwic291cmNlLW1hcC1zdXBwb3J0XCIpLmluc3RhbGwoKVxuXG5tb2R1bGUuZXhwb3J0cyA9ICh3aGF0Li4uKSAtPlxuICB0aHJvdyBuZXcgRXJyb3IgXCJlcnJvclwiXG4iXX0=